# Generated by Django 3.2.9 on 2021-11-24 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamaleon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='preciounitario',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,6}$')]),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='precioventa',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,6}$')]),
        ),
    ]
