# Generated by Django 3.2.9 on 2021-11-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamaleon', '0002_auto_20211124_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='preciounitario',
            field=models.FloatField(max_length=6),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='precioventa',
            field=models.FloatField(max_length=6),
        ),
    ]
